
"use client"

import React, { createContext, useContext, useState, useEffect } from 'react'

interface LanguageContextType {
  language: string
  setLanguage: (lang: string) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations: Record<string, Record<string, string>> = {
  en: {
    'site.title': 'Placid Asia - Professional Acoustic Solutions',
    'site.description': 'Leading supplier of acoustic measurement equipment and sound testing solutions in Asia',
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.categories': 'Categories',
    'nav.brands': 'Brands',
    'nav.applications': 'Applications',
    'nav.measurementSets': 'Measurement Sets',
    'nav.about': 'About',
    'nav.guides': 'Buyer Guides',
    'nav.blog': 'Blog',
    'nav.contact': 'Contact',
    'nav.admin': 'Admin',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    'nav.cart': 'Cart',
    'hero.title': 'Professional Acoustic Measurement Solutions',
    'hero.subtitle': 'Precision instruments for sound measurement, vibration analysis, and acoustic testing across industries',
    'hero.cta': 'Explore Products',
    'products.title': 'Our Products',
    'products.subtitle': 'Comprehensive range of acoustic measurement equipment',
    'products.search': 'Search products...',
    'products.filter': 'Filter by category',
    'products.sort': 'Sort by',
    'products.sort.name': 'Name',
    'products.sort.category': 'Category',
    'products.addToCart': 'Add to Cart',
    'products.contactForQuote': 'Contact for Quote',
    'products.viewDetails': 'View Details',
    'products.downloadPDF': 'Download PDF',
    'categories.title': 'Product Categories',
    'categories.products': 'products',
    'categories.label': 'Categories',
    'categories.backToCategories': 'Back to Categories',
    'categories.inCategory': 'products in this category',
    'cart.title': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.quantity': 'Quantity',
    'cart.remove': 'Remove',
    'cart.total': 'Total Items',
    'cart.loading': 'Loading cart...',
    'cart.startShopping': 'Start shopping to add items to your cart',
    'cart.continueShopping': 'Continue Shopping',
    'cart.itemsInCart': 'items in your cart',
    'cart.clearCart': 'Clear Cart',
    'cart.requestQuote': 'Request Quote',
    'cart.sku': 'SKU:',
    'cart.category': 'Category:',
    'contact.title': 'Contact Us',
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.phone': 'Phone',
    'contact.company': 'Company',
    'contact.subject': 'Subject',
    'contact.message': 'Message',
    'contact.submit': 'Send Message',
    'contact.success': 'Thank you! Your message has been sent.',
    'contact.description': 'Get in touch with our team for product inquiries, technical support, or partnership opportunities',
    'contact.sendMessage': 'Send us a message',
    'contact.namePlaceholder': 'Your full name',
    'contact.emailPlaceholder': 'your.email@company.com',
    'contact.phonePlaceholder': '+66 xx xxx xxxx',
    'contact.companyPlaceholder': 'Your company name',
    'contact.productSku': 'Product SKU',
    'contact.subjectPlaceholder': 'How can we help you?',
    'contact.messagePlaceholder': 'Please provide details about your inquiry...',
    'contact.sending': 'Sending...',
    'contact.info': 'Contact Information',
    'contact.email.label': 'Email',
    'contact.phone.label': 'Phone',
    'contact.address': 'Address',
    'contact.address.value': '6/56 Poemsin Road Soi 42, Sai Mai, 10220 Bangkok, Thailand',
    'contact.businessHours': 'Business Hours',
    'contact.monday-friday': 'Monday - Friday',
    'contact.saturday': 'Saturday',
    'contact.sunday': 'Sunday',
    'contact.closed': 'Closed',
    'contact.formDescription': 'Fill out the form below and we\'ll get back to you as soon as possible.',
    'contact.infoDescription': 'You can also reach us through these channels',
    'contact.whyChooseUs': 'Why Choose Placid Asia?',
    'contact.reason1': 'Fast response within 24 hours',
    'contact.reason2': 'Expert technical support',
    'contact.reason3': 'Tailored solutions for your needs',
    'contact.reason4': 'Long-term partnership commitment',
    'footer.about': 'About Placid Asia',
    'footer.description': 'Leading supplier of professional acoustic measurement equipment and solutions across Asia Pacific region.',
    'footer.links': 'Quick Links',
    'footer.contact': 'Contact Info',
    'footer.followUs': 'Follow us on social media',
    'footer.rights': 'All rights reserved',
    'admin.title': 'Admin Dashboard',
    'admin.products': 'Products',
    'admin.categories': 'Categories',
    'admin.inquiries': 'Inquiries',
    'admin.users': 'Users',
    'admin.totalProducts': 'Total Products',
    'admin.withPricing': 'with pricing',
    'admin.withoutPricing': 'without',
    'admin.activeCategories': 'Active product categories',
    'admin.totalInquiries': 'Total Inquiries',
    'admin.customerInquiries': 'Customer inquiries received',
    'admin.adminUsers': 'Admin Users',
    'admin.activeAccounts': 'Active admin accounts',
    'admin.dashboard': 'Admin Dashboard',
    'admin.welcomeBack': 'Welcome back',
    'admin.manageMessage': 'Manage your acoustic equipment catalog.',
    'admin.recentInquiries': 'Recent Inquiries',
    'admin.product': 'Product:',
    'admin.noInquiries': 'No inquiries yet',
    'admin.quickActions': 'Quick Actions',
    'admin.productManagement': 'Product Management',
    'admin.productManagementDesc': 'Add new products, update pricing, manage categories',
    'admin.inquiryManagement': 'Inquiry Management',
    'admin.inquiryManagementDesc': 'Review customer inquiries and product requests',
    'admin.contentUpdates': 'Content Updates',
    'admin.contentUpdatesDesc': 'Update product descriptions, images, and documentation',
    'product.documents': 'Documents',
    'product.getInfo': 'Get More Information',
    'product.contactPlacid': 'Contact Placid Asia',
    'product.manufacturerPage': 'Manufacturer Page',
    'product.description': 'Description',
    'product.applications': 'Typical Applications',
    'product.features': 'Key Features',
    'product.specifications': 'Technical Specifications',
    'product.resources': 'Resources & Downloads',
    'product.overview': 'In-Depth Overview',
    'product.applicationsDesc': 'Common use cases and application scenarios for this product',
    'product.featuresTitle': 'Key Features & Benefits',
    'product.featuresDesc': 'What makes this product stand out from the competition',
    'product.specsTitle': 'Technical Specifications',
    'product.specsDesc': 'Detailed technical parameters and performance characteristics',
    'product.downloadDoc': 'Download Documentation',
    'product.viewManual': 'View Product Manual',
    'product.relatedProducts': 'Related Products',
    'product.relatedDesc': 'You might also be interested in these products',
    'product.parameter': 'Parameter',
    'product.specification': 'Specification',
    'common.back': 'Back to Products',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    
    
    // FAQ Page
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Find answers to common questions about our products, services, and support',
    'faq.stillHaveQuestions': 'Still have questions?',
    'faq.contactUs': 'Contact our team',
    'faq.chatWithAI': 'Chat with AI Assistant',
    'faq.general': 'General Questions',
    'faq.technical': 'Technical Questions',
    'faq.building': 'Building Acoustics',
    'faq.monitoring': 'Noise Monitoring',
    'faq.ordering': 'Ordering & Delivery',
    'faq.afterSales': 'After-Sales Support',
    
    // Measurement Sets Page
    'measurementSets.title': 'Complete Measurement Sets',
    'measurementSets.subtitle': 'Professional Turnkey Measurement Systems',
    'measurementSets.intro': 'Pre-configured, ready-to-use measurement systems for your specific application',
    'measurementSets.whyChoose': 'Why Choose Complete Sets',
    'measurementSets.preConfigured': 'Pre-configured Systems',
    'measurementSets.compliance': 'Standards Compliance',
    'measurementSets.costEffective': 'Cost-Effective',
    'measurementSets.expertSupport': 'Expert Support',
    'measurementSets.available': 'Available Measurement Systems',
    'measurementSets.howToOrder': 'How to Order',
    'measurementSets.stepConsult': 'Consultation',
    'measurementSets.stepConfig': 'Configuration',
    'measurementSets.stepQuote': 'Quotation',
    'measurementSets.stepDelivery': 'Delivery & Training',
    'measurementSets.cta': 'Request a Custom System',
    'measurementSets.ctaSubtitle': 'Contact us for a consultation',
    'measurementSets.contactForConsult': 'Contact for Consultation',
    
    // Homepage
    'home.companyNameEN': 'PLACID Asia Co., Ltd',
    'home.companyNameTH': 'บริษัท เพลซิด เอเซีย จำกัด',
    'home.heroTitle1': 'Professional Acoustic',
    'home.heroTitle2': 'Measurement Solutions',
    'home.heroSubtitle': 'Precision instruments for sound measurement, vibration analysis, and acoustic testing across industries',
    'home.exploreProducts': 'Explore Products',
    'home.contactUs': 'Contact Us',
    'home.statsProducts': 'Products',
    'home.statsCategories': 'Categories',
    'home.statsYears': 'Years Experience',
    'home.statsCustomers': 'Happy Customers',
    'home.whyChooseTitle': 'Why Choose Placid Asia?',
    'home.whyChooseSubtitle': 'Leading supplier of professional acoustic measurement equipment with comprehensive solutions',
    'home.feature1Title': 'Precision Measurement',
    'home.feature1Desc': 'High-accuracy instruments for professional acoustic and vibration analysis',
    'home.feature2Title': 'Industry Standards',
    'home.feature2Desc': 'Certified equipment meeting international measurement standards',
    'home.feature3Title': 'Expert Support',
    'home.feature3Desc': 'Technical expertise and comprehensive after-sales support',
    'home.categoriesTitle': 'Product Categories',
    'home.categoriesSubtitle': 'Comprehensive range of acoustic measurement equipment',
    'home.viewAllCategories': 'View All Categories',
    'home.applicationAreasTitle': 'Application Areas',
    'home.applicationAreasSubtitle': 'Our equipment serves diverse industries and applications',
    'home.app1Title': 'Environmental Monitoring',
    'home.app1Desc': 'Noise pollution assessment and environmental compliance',
    'home.app2Title': 'Industrial Testing',
    'home.app2Desc': 'Quality control and product development testing',
    'home.app3Title': 'Research & Development',
    'home.app3Desc': 'Advanced acoustic research and scientific applications',
    'home.featuredProducts': 'Featured Products',
    'home.featuredProductsSubtitle': 'Discover our latest and most popular acoustic measurement equipment',
    'home.browseByCategory': 'Browse by Product Category',
    'home.viewAllBrands': 'View All Brands',
    'home.trustedBrands': 'Trusted Brands',
    'home.learnMore': 'Learn More',
    'home.product': 'product',
    'home.products': 'products',
    
    // Products Page
    'products.heroBadge': 'Complete Product Catalog',
    'products.heroTitle': 'Professional Acoustic & Vibration Measurement Equipment',
    'products.heroSubtitle': 'Discover our comprehensive range of sound level meters, environmental noise monitors, vibration analyzers, and acoustic test systems from world-leading manufacturers. Serving Thailand and Southeast Asia with precision measurement solutions since 1990.',
    'products.badge100Products': '100+ Professional Products',
    'products.badge15Brands': '15+ Leading Brands',
    'products.badgeISO': 'ISO Certified Equipment',
    'products.badgeSupport': 'Local Support & Calibration',
    'products.whyChooseTitle': 'Why Choose Placid Asia Equipment?',
    'products.whyChooseSubtitle': 'As Thailand\'s leading distributor of professional acoustic and vibration measurement equipment, we provide unmatched quality, support, and expertise.',
    'products.card1Title': 'Certified & Calibrated',
    'products.card1Desc': 'All equipment comes with factory calibration certificates and meets international standards (IEC 61672, ISO 8041)',
    'products.card2Title': 'Warranty & Support',
    'products.card2Desc': 'Comprehensive warranty coverage with local technical support and in-country calibration services',
    'products.card3Title': 'Expert Consultation',
    'products.card3Desc': 'Free technical consultation to help you select the right equipment for your specific application',
    'products.card4Title': 'Fast Delivery',
    'products.card4Desc': 'Quick delivery across Thailand and Southeast Asia with secure packaging and tracking',
    'products.browseByCategoryTitle': 'Browse by Product Category',
    'products.browseByCategorySubtitle': 'From portable sound level meters to advanced acoustic camera systems, find exactly what you need for environmental monitoring, building acoustics, industrial noise control, or vibration analysis.',
    'products.slm.title': 'Sound Level Meters',
    'products.slm.desc': 'Class 1 and Class 2 precision sound level meters for environmental, occupational, and building acoustics measurements. Portable and hand-held models available.',
    'products.slm.bullet1': 'IEC 61672 Class 1 & Class 2 certified',
    'products.slm.bullet2': 'Real-time octave band analysis',
    'products.slm.bullet3': 'Data logging and wireless connectivity',
    'products.slm.bullet4': 'Calibration certificates included',
    'products.noise.title': 'Noise Monitoring Systems',
    'products.noise.desc': 'Permanent and temporary noise monitoring stations for construction sites, airports, industrial facilities, and environmental compliance monitoring.',
    'products.noise.bullet1': '24/7 continuous monitoring capability',
    'products.noise.bullet2': 'Weather-resistant outdoor enclosures',
    'products.noise.bullet3': 'Remote access and alerting',
    'products.noise.bullet4': 'Compliance reporting software',
    'products.vibration.title': 'Vibration Analysis Equipment',
    'products.vibration.desc': 'Advanced vibration meters, analyzers, and monitoring systems for structural health monitoring, industrial machinery analysis, and building vibration assessment.',
    'products.vibration.bullet1': 'Human comfort vibration (ISO 2631)',
    'products.vibration.bullet2': 'Building damage assessment (DIN 4150)',
    'products.vibration.bullet3': 'Machinery condition monitoring',
    'products.vibration.bullet4': 'Triaxial accelerometer systems',
    'products.material.title': 'Acoustic Material Testing',
    'products.material.desc': 'Professional equipment for testing sound absorption, sound insulation, and transmission loss of building materials, panels, and acoustic treatments.',
    'products.material.bullet1': 'Impedance tube systems (ISO 10534)',
    'products.material.bullet2': 'Transmission loss measurement',
    'products.material.bullet3': 'Absorption coefficient testing',
    'products.material.bullet4': 'Laboratory and field systems',
    'products.calibration.title': 'Acoustic Calibration Systems',
    'products.calibration.desc': 'Precision acoustic calibrators, pistonphones, and calibration systems for maintaining measurement accuracy and compliance with international standards.',
    'products.calibration.bullet1': 'Class 1 and LS standards',
    'products.calibration.bullet2': 'Multiple frequency options',
    'products.calibration.bullet3': 'IEC 60942 compliant',
    'products.calibration.bullet4': 'Traceable calibration',
    'products.sensors.title': 'Noise & Vibration Sensors',
    'products.sensors.desc': 'High-performance measurement microphones, accelerometers, and transducers for precision acoustic and vibration measurements.',
    'products.sensors.bullet1': 'Free-field and pressure-field microphones',
    'products.sensors.bullet2': 'Piezoelectric and MEMS accelerometers',
    'products.sensors.bullet3': 'Wide frequency range coverage',
    'products.sensors.bullet4': 'Factory calibration certificates',
    
    // Applications Page
    'applications.title': 'Acoustic, Noise & Vibration Testing Solutions',
    'applications.subtitle': 'Find the right equipment and systems for your application, from building acoustics to industrial testing',
    'applications.viewDetails': 'View Details',
    
    // Guides Page
    'guides.title': 'Expert Buyer Guides',
    'guides.subtitle': 'Comprehensive guides to help you choose the right acoustic, noise, and vibration measurement equipment for your needs',
    'guides.readTime': 'read time',
    'guides.level': 'Level',
    'guides.category': 'Category',
    'guides.readGuide': 'Read Guide',
    'guides.allGuides': 'All Guides',
    'guides.beginner': 'Beginner',
    'guides.intermediate': 'Intermediate',
    'guides.advanced': 'Advanced',
    
    // Solutions Pages
    'solutions.impedanceTube.title': 'Impedance Tube ISO 10534-2 & ASTM E2611',
    'solutions.impedanceTube.subtitle': 'Professional impedance tube systems for sound absorption coefficient and transmission loss measurement per ISO 10534-2 and ASTM E2611',
    'solutions.impedanceTube.compliant': 'ISO 10534-2 & ASTM E2611 Compliant',
    'solutions.impedanceTube.accurate': 'Fast & Accurate Measurements',
    'solutions.impedanceTube.support': 'Local Support & Calibration in Thailand',
    'solutions.impedanceTube.standards': 'Standards & Applications',
    'solutions.impedanceTube.iso10534': 'ISO 10534-2: Transfer function method for measuring sound absorption coefficient',
    'solutions.impedanceTube.astm': 'ASTM E2611: Standard method for measuring acoustic properties of materials',
    'solutions.impedanceTube.features': 'Technical Features',
    'solutions.impedanceTube.fastAccurate': 'Fast & Accurate',
    'solutions.impedanceTube.fastDesc': 'Results in minutes, no anechoic chamber required',
    'solutions.impedanceTube.broadFreq': 'Broad Frequency Range',
    'solutions.impedanceTube.broadFreqDesc': 'Measure from 50 Hz to 6400 Hz with multiple tube sizes',
    'solutions.impedanceTube.recognized': 'Internationally Recognized',
    'solutions.impedanceTube.recognizedDesc': 'Accepted results for certification and research',
    'solutions.impedanceTube.products': 'Recommended Products',
    'solutions.impedanceTube.consultation': 'Need a Consultation?',
    'solutions.impedanceTube.consultationDesc': 'Our expert team is ready to help you select the right impedance tube system',
    'solutions.impedanceTube.contactExpert': 'Contact Expert',
    'solutions.impedanceTube.viewGuides': 'View Buyer Guides',
    
    'solutions.class1Mic.title': 'Class 1 Measurement Microphones for Thailand',
    'solutions.class1Mic.subtitle': 'High-precision PMP21 Series measurement microphones compliant with IEC 61094-4, with individual calibration and local support in Thailand',
    'solutions.class1Mic.precision': 'Highest Precision',
    'solutions.class1Mic.precisionDesc': 'IEC 61672 Class 1 and IEC 61094-4 compliant for the most accurate measurements',
    'solutions.class1Mic.calibration': 'Individual Calibration',
    'solutions.class1Mic.calibrationDesc': 'Each microphone comes with a traceable calibration certificate',
    'solutions.class1Mic.localSupport': 'Local Support in Thailand',
    'solutions.class1Mic.localSupportDesc': 'Thai after-sales service, calibration, and technical support',
    'solutions.class1Mic.techSpecs': 'Technical Specifications',
    'solutions.class1Mic.pmp21Series': 'PMP21 Series - Class 1 Measurement Microphone',
    'solutions.class1Mic.freqRange': 'Frequency Range: 3.15 Hz to 20 kHz',
    'solutions.class1Mic.sensitivity': 'Sensitivity: 50 mV/Pa ±2 dB',
    'solutions.class1Mic.dynamic': 'Dynamic Range: 15 dB(A) to 146 dB',
    'solutions.class1Mic.standards': 'Standards: IEC 61094-4, IEC 61672 Class 1',
    'solutions.class1Mic.compatible': 'Compatible Sound Level Meters',
    'solutions.class1Mic.applications': 'Common Applications',
    'solutions.class1Mic.buildingAcoustics': 'Building acoustics testing (ISO 16283)',
    'solutions.class1Mic.environmental': 'Environmental noise monitoring',
    'solutions.class1Mic.industrial': 'Industrial noise measurement',
    'solutions.class1Mic.laboratory': 'Research and laboratory measurements',
    'solutions.class1Mic.expertAdvice': 'Need Expert Advice?',
    'solutions.class1Mic.expertAdviceDesc': 'Contact us to discuss your sound measurement needs and find the right microphone solution',
    'solutions.class1Mic.getQuote': 'Get Quote',
    'solutions.class1Mic.browseAll': 'Browse All Products',
    
    'solutions.factoryNoise.title': 'Factory Noise Monitoring Systems',
    'solutions.factoryNoise.subtitle': 'Continuous noise monitoring solutions for industrial facilities, worker safety, and environmental compliance in Thailand',
    'solutions.factoryNoise.viewSolutions': 'View Solutions',
    'solutions.factoryNoise.requestConsultation': 'Request Consultation',
    
    'solutions.eolTesting.title': 'End-of-Line Acoustic Testing',
    'solutions.eolTesting.subtitle': 'Automated acoustic testing systems for production quality control, combining impedance tubes and precision measurement microphones',
    'solutions.eolTesting.viewEquipment': 'View Equipment',
    'solutions.eolTesting.requestConsultation': 'Request Consultation',
  },
  th: {
    'site.title': 'Placid Asia - โซลูชันอะคูสติกระดับมืออาชีพ',
    'site.description': 'ผู้จัดจำหน่ายชั้นนำของอุปกรณ์วัดเสียงและโซลูชันการทดสอบเสียงในเอเชีย',
    'nav.home': 'หน้าแรก',
    'nav.products': 'ผลิตภัณฑ์',
    'nav.categories': 'หมวดหมู่',
    'nav.brands': 'แบรนด์',
    'nav.applications': 'การใช้งาน',
    'nav.measurementSets': 'ชุดอุปกรณ์วัดครบชุด',
    'nav.about': 'เกี่ยวกับเรา',
    'nav.guides': 'คู่มือผู้ซื้อ',
    'nav.blog': 'บล็อก',
    'nav.contact': 'ติดต่อ',
    'nav.admin': 'ผู้ดูแลระบบ',
    'nav.login': 'เข้าสู่ระบบ',
    'nav.logout': 'ออกจากระบบ',
    'nav.cart': 'ตะกร้า',
    'hero.title': 'โซลูชันการวัดเสียงระดับมืออาชีพ',
    'hero.subtitle': 'เครื่องมือแม่นยำสำหรับการวัดเสียง การวิเคราะห์การสั่นสะเทือน และการทดสอบอะคูสติกในอุตสาหกรรมต่างๆ',
    'hero.cta': 'ดูผลิตภัณฑ์',
    'products.title': 'ผลิตภัณฑ์ของเรา',
    'products.subtitle': 'ผลิตภัณฑ์อุปกรณ์วัดเสียงครบครัน',
    'products.search': 'ค้นหาผลิตภัณฑ์...',
    'products.filter': 'กรองตามหมวดหมู่',
    'products.sort': 'เรียงตาม',
    'products.sort.name': 'ชื่อ',
    'products.sort.category': 'หมวดหมู่',
    'products.addToCart': 'เพิ่มลงตะกร้า',
    'products.contactForQuote': 'ติดต่อสอบถามราคา',
    'products.viewDetails': 'ดูรายละเอียด',
    'products.downloadPDF': 'ดาวน์โหลด PDF',
    'categories.title': 'หมวดหมู่ผลิตภัณฑ์',
    'categories.products': 'ผลิตภัณฑ์',
    'categories.label': 'หมวดหมู่',
    'categories.backToCategories': 'กลับไปที่หมวดหมู่',
    'categories.inCategory': 'ผลิตภัณฑ์ในหมวดหมู่นี้',
    'cart.title': 'ตะกร้าสินค้า',
    'cart.empty': 'ตะกร้าของคุณว่างเปล่า',
    'cart.quantity': 'จำนวน',
    'cart.remove': 'ลบ',
    'cart.total': 'จำนวนรายการทั้งหมด',
    'cart.loading': 'กำลังโหลดตะกร้า...',
    'cart.startShopping': 'เริ่มช็อปปิ้งเพื่อเพิ่มสินค้าในตะกร้าของคุณ',
    'cart.continueShopping': 'ช็อปปิ้งต่อ',
    'cart.itemsInCart': 'รายการในตะกร้าของคุณ',
    'cart.clearCart': 'ล้างตะกร้า',
    'cart.requestQuote': 'ขอใบเสนอราคา',
    'cart.sku': 'รหัสสินค้า:',
    'cart.category': 'หมวดหมู่:',
    'contact.title': 'ติดต่อเรา',
    'contact.name': 'ชื่อ',
    'contact.email': 'อีเมล',
    'contact.phone': 'โทรศัพท์',
    'contact.company': 'บริษัท',
    'contact.subject': 'หัวข้อ',
    'contact.message': 'ข้อความ',
    'contact.submit': 'ส่งข้อความ',
    'contact.success': 'ขอบคุณ! ข้อความของคุณถูกส่งแล้ว',
    'contact.description': 'ติดต่อทีมของเราสำหรับข้อมูลผลิตภัณฑ์ การสนับสนุนทางเทคนิค หรือโอกาสในการเป็นพันธมิตร',
    'contact.sendMessage': 'ส่งข้อความถึงเรา',
    'contact.namePlaceholder': 'ชื่อเต็มของคุณ',
    'contact.emailPlaceholder': 'อีเมลของคุณ@บริษัท.com',
    'contact.phonePlaceholder': '+66 xx xxx xxxx',
    'contact.companyPlaceholder': 'ชื่อบริษัทของคุณ',
    'contact.productSku': 'รหัสผลิตภัณฑ์',
    'contact.subjectPlaceholder': 'เราสามารถช่วยคุณอย่างไร?',
    'contact.messagePlaceholder': 'โปรดระบุรายละเอียดเกี่ยวกับคำถามของคุณ...',
    'contact.sending': 'กำลังส่ง...',
    'contact.info': 'ข้อมูลติดต่อ',
    'contact.email.label': 'อีเมล',
    'contact.phone.label': 'โทรศัพท์',
    'contact.address': 'ที่อยู่',
    'contact.address.value': '6/56 ถนนเปมศิน ซอย 42, สายไหม, กรุงเทพฯ 10220, ประเทศไทย',
    'contact.businessHours': 'เวลาทำการ',
    'contact.monday-friday': 'จันทร์ - ศุกร์',
    'contact.saturday': 'เสาร์',
    'contact.sunday': 'อาทิตย์',
    'contact.closed': 'ปิดทำการ',
    'contact.formDescription': 'กรอกแบบฟอร์มด้านล่างและเราจะติดต่อกลับโดยเร็วที่สุด',
    'contact.infoDescription': 'คุณสามารถติดต่อเราผ่านช่องทางเหล่านี้',
    'contact.whyChooseUs': 'ทำไมต้องเลือก Placid Asia?',
    'contact.reason1': 'ตอบกลับอย่างรวดเร็วภายใน 24 ชั่วโมง',
    'contact.reason2': 'การสนับสนุนทางเทคนิคจากผู้เชี่ยวชาญ',
    'contact.reason3': 'โซลูชันที่ปรับแต่งตามความต้องการของคุณ',
    'contact.reason4': 'มุ่งมั่นในความร่วมมือระยะยาว',
    'footer.about': 'เกี่ยวกับ Placid Asia',
    'footer.description': 'ผู้จัดจำหน่ายชั้นนำของอุปกรณ์วัดเสียงระดับมืออาชีพและโซลูชันต่างๆ ในภูมิภาคเอเชียแปซิฟิก',
    'footer.links': 'ลิงค์ด่วน',
    'footer.contact': 'ข้อมูลติดต่อ',
    'footer.followUs': 'ติดตามเราบนโซเชียลมีเดีย',
    'footer.rights': 'สงวนลิขสิทธิ์',
    'admin.title': 'แดชบอร์ดผู้ดูแลระบบ',
    'admin.products': 'ผลิตภัณฑ์',
    'admin.categories': 'หมวดหมู่',
    'admin.inquiries': 'คำถาม',
    'admin.users': 'ผู้ใช้',
    'admin.totalProducts': 'ผลิตภัณฑ์ทั้งหมด',
    'admin.withPricing': 'มีราคา',
    'admin.withoutPricing': 'ไม่มีราคา',
    'admin.activeCategories': 'หมวดหมู่ผลิตภัณฑ์ที่ใช้งาน',
    'admin.totalInquiries': 'คำถามทั้งหมด',
    'admin.customerInquiries': 'คำถามจากลูกค้าที่ได้รับ',
    'admin.adminUsers': 'ผู้ดูแลระบบ',
    'admin.activeAccounts': 'บัญชีผู้ดูแลที่ใช้งาน',
    'admin.dashboard': 'แดชบอร์ดผู้ดูแลระบบ',
    'admin.welcomeBack': 'ยินดีต้อนรับกลับ',
    'admin.manageMessage': 'จัดการแคตตาล็อกอุปกรณ์อะคูสติกของคุณ',
    'admin.recentInquiries': 'คำถามล่าสุด',
    'admin.product': 'ผลิตภัณฑ์:',
    'admin.noInquiries': 'ยังไม่มีคำถาม',
    'admin.quickActions': 'การดำเนินการด่วน',
    'admin.productManagement': 'การจัดการผลิตภัณฑ์',
    'admin.productManagementDesc': 'เพิ่มผลิตภัณฑ์ใหม่ อัพเดทราคา จัดการหมวดหมู่',
    'admin.inquiryManagement': 'การจัดการคำถาม',
    'admin.inquiryManagementDesc': 'ตรวจสอบคำถามจากลูกค้าและคำขอผลิตภัณฑ์',
    'admin.contentUpdates': 'การอัพเดทเนื้อหา',
    'admin.contentUpdatesDesc': 'อัพเดทคำอธิบายผลิตภัณฑ์ รูปภาพ และเอกสาร',
    'product.documents': 'เอกสาร',
    'product.getInfo': 'ขอข้อมูลเพิ่มเติม',
    'product.contactPlacid': 'ติดต่อ Placid Asia',
    'product.manufacturerPage': 'หน้าผู้ผลิต',
    'product.description': 'รายละเอียด',
    'product.applications': 'การใช้งานทั่วไป',
    'product.features': 'คุณสมบัติสำคัญ',
    'product.specifications': 'ข้อมูลทางเทคนิค',
    'product.resources': 'ทรัพยากรและดาวน์โหลด',
    'product.overview': 'ภาพรวมโดยละเอียด',
    'product.applicationsDesc': 'กรณีการใช้งานทั่วไปและสถานการณ์การใช้งานสำหรับผลิตภัณฑ์นี้',
    'product.featuresTitle': 'คุณสมบัติและประโยชน์หลัก',
    'product.featuresDesc': 'สิ่งที่ทำให้ผลิตภัณฑ์นี้โดดเด่นจากคู่แข่ง',
    'product.specsTitle': 'ข้อมูลทางเทคนิค',
    'product.specsDesc': 'พารามิเตอร์ทางเทคนิคและลักษณะประสิทธิภาพโดยละเอียด',
    'product.downloadDoc': 'ดาวน์โหลดเอกสาร',
    'product.viewManual': 'ดูคู่มือผลิตภัณฑ์',
    'product.relatedProducts': 'ผลิตภัณฑ์ที่เกี่ยวข้อง',
    'product.relatedDesc': 'คุณอาจสนใจผลิตภัณฑ์เหล่านี้',
    'product.parameter': 'พารามิเตอร์',
    'product.specification': 'ข้อกำหนด',
    'common.back': 'กลับไปที่ผลิตภัณฑ์',
    'common.loading': 'กำลังโหลด...',
    'common.error': 'ข้อผิดพลาด',
    'common.success': 'สำเร็จ',
    
    // FAQ Page Thai
    'faq.title': 'คำถามที่พบบ่อย',
    'faq.subtitle': 'ค้นหาคำตอบสำหรับคำถามทั่วไปเกี่ยวกับผลิตภัณฑ์ บริการ และการสนับสนุนของเรา',
    'faq.stillHaveQuestions': 'ยังมีคำถามอยู่ไหม?',
    'faq.contactUs': 'ติดต่อทีมของเรา',
    'faq.chatWithAI': 'แชทกับ AI Assistant',
    'faq.general': 'คำถามทั่วไป',
    'faq.technical': 'คำถามทางเทคนิค',
    'faq.building': 'อะคูสติกอาคาร',
    'faq.monitoring': 'การตรวจวัดเสียง',
    'faq.ordering': 'การสั่งซื้อและการจัดส่ง',
    'faq.afterSales': 'การสนับสนุนหลังการขาย',
    
    // Measurement Sets Page Thai
    'measurementSets.title': 'ชุดอุปกรณ์วัดครบชุด',
    'measurementSets.subtitle': 'ระบบวัดแบบครบชุดสำหรับมืออาชีพ',
    'measurementSets.intro': 'ระบบวัดที่กำหนดค่าไว้ล่วงหน้าและพร้อมใช้งานสำหรับการใช้งานเฉพาะของคุณ',
    'measurementSets.whyChoose': 'ทำไมต้องเลือกชุดครบชุด',
    'measurementSets.preConfigured': 'ระบบที่กำหนดค่าไว้ล่วงหน้า',
    'measurementSets.compliance': 'การปฏิบัติตามมาตรฐาน',
    'measurementSets.costEffective': 'คุ้มค่า',
    'measurementSets.expertSupport': 'การสนับสนุนจากผู้เชี่ยวชาญ',
    'measurementSets.available': 'ระบบวัดที่มีจำหน่าย',
    'measurementSets.howToOrder': 'วิธีการสั่งซื้อ',
    'measurementSets.stepConsult': 'ปรึกษา',
    'measurementSets.stepConfig': 'กำหนดค่า',
    'measurementSets.stepQuote': 'ใบเสนอราคา',
    'measurementSets.stepDelivery': 'จัดส่งและอบรม',
    'measurementSets.cta': 'ขอระบบที่กำหนดเอง',
    'measurementSets.ctaSubtitle': 'ติดต่อเราเพื่อปรึกษา',
    'measurementSets.contactForConsult': 'ติดต่อเพื่อปรึกษา',
    
    // Homepage Thai
    'home.companyNameEN': 'PLACID Asia Co., Ltd',
    'home.companyNameTH': 'บริษัท เพลซิด เอเซีย จำกัด',
    'home.heroTitle1': 'โซลูชันการวัดเสียง',
    'home.heroTitle2': 'ระดับมืออาชีพ',
    'home.heroSubtitle': 'เครื่องมือแม่นยำสำหรับการวัดเสียง การวิเคราะห์การสั่นสะเทือน และการทดสอบอะคูสติกในอุตสาหกรรมต่างๆ',
    'home.exploreProducts': 'สำรวจผลิตภัณฑ์',
    'home.contactUs': 'ติดต่อเรา',
    'home.statsProducts': 'ผลิตภัณฑ์',
    'home.statsCategories': 'หมวดหมู่',
    'home.statsYears': 'ปีของประสบการณ์',
    'home.statsCustomers': 'ลูกค้าที่พึงพอใจ',
    'home.whyChooseTitle': 'ทำไมต้องเลือก Placid Asia?',
    'home.whyChooseSubtitle': 'ผู้จัดจำหน่ายชั้นนำของอุปกรณ์วัดเสียงระดับมืออาชีพพร้อมโซลูชันที่ครบครัน',
    'home.feature1Title': 'การวัดที่แม่นยำ',
    'home.feature1Desc': 'เครื่องมือความแม่นยำสูงสำหรับการวิเคราะห์เสียงและการสั่นสะเทือนระดับมืออาชีพ',
    'home.feature2Title': 'มาตรฐานอุตสาหกรรม',
    'home.feature2Desc': 'อุปกรณ์ที่ได้รับการรับรองตามมาตรฐานการวัดระดับสากล',
    'home.feature3Title': 'การสนับสนุนจากผู้เชี่ยวชาญ',
    'home.feature3Desc': 'ความเชี่ยวชาญทางเทคนิคและการสนับสนุนหลังการขายที่ครบครัน',
    'home.categoriesTitle': 'หมวดหมู่ผลิตภัณฑ์',
    'home.categoriesSubtitle': 'ผลิตภัณฑ์อุปกรณ์วัดเสียงครบครัน',
    'home.viewAllCategories': 'ดูหมวดหมู่ทั้งหมด',
    'home.applicationAreasTitle': 'พื้นที่การใช้งาน',
    'home.applicationAreasSubtitle': 'อุปกรณ์ของเราให้บริการอุตสาหกรรมและการใช้งานที่หลากหลาย',
    'home.app1Title': 'การตรวจวัดสิ่งแวดล้อม',
    'home.app1Desc': 'การประเมินมลพิษทางเสียงและการปฏิบัติตามข้อกำหนดด้านสิ่งแวดล้อม',
    'home.app2Title': 'การทดสอบอุตสาหกรรม',
    'home.app2Desc': 'การควบคุมคุณภาพและการทดสอบการพัฒนาผลิตภัณฑ์',
    'home.app3Title': 'วิจัยและพัฒนา',
    'home.app3Desc': 'การวิจัยอะคูสติกขั้นสูงและการใช้งานทางวิทยาศาสตร์',
    'home.featuredProducts': 'ผลิตภัณฑ์แนะนำ',
    'home.featuredProductsSubtitle': 'ค้นพบอุปกรณ์วัดเสียงล่าสุดและยอดนิยมของเรา',
    'home.browseByCategory': 'เรียกดูตามหมวดหมู่ผลิตภัณฑ์',
    'home.viewAllBrands': 'ดูแบรนด์ทั้งหมด',
    'home.trustedBrands': 'แบรนด์ที่เชื่อถือได้',
    'home.learnMore': 'เรียนรู้เพิ่มเติม',
    'home.product': 'ผลิตภัณฑ์',
    'home.products': 'ผลิตภัณฑ์',
    
    // Products Page Thai
    'products.heroBadge': 'แคตตาล็อกผลิตภัณฑ์ฉบับสมบูรณ์',
    'products.heroTitle': 'อุปกรณ์วัดเสียงและการสั่นสะเทือนระดับมืออาชีพ',
    'products.heroSubtitle': 'ค้นพบผลิตภัณฑ์ครบครันของเรา ตั้งแต่เครื่องวัดระดับเสียง เครื่องตรวจวัดเสียงสิ่งแวดล้อม เครื่องวิเคราะห์การสั่นสะเทือน และระบบทดสอบอะคูสติกจากผู้ผลิตชั้นนำระดับโลก ให้บริการประเทศไทยและเอเชียตะวันออกเฉียงใต้ด้วยโซลูชันการวัดที่แม่นยำตั้งแต่ปี 1990',
    'products.badge100Products': 'ผลิตภัณฑ์มืออาชีพกว่า 100 รายการ',
    'products.badge15Brands': 'แบรนด์ชั้นนำกว่า 15 แบรนด์',
    'products.badgeISO': 'อุปกรณ์ที่ได้รับมาตรฐาน ISO',
    'products.badgeSupport': 'บริการและการสอบเทียบในประเทศ',
    'products.whyChooseTitle': 'ทำไมต้องเลือกอุปกรณ์ของ Placid Asia?',
    'products.whyChooseSubtitle': 'ในฐานะผู้จัดจำหน่ายชั้นนำของอุปกรณ์วัดเสียงและการสั่นสะเทือนระดับมืออาชีพในประเทศไทย เรามอบคุณภาพ การสนับสนุน และความเชี่ยวชาญที่เหนือกว่า',
    'products.card1Title': 'ได้รับการรับรองและสอบเทียบ',
    'products.card1Desc': 'อุปกรณ์ทั้งหมดมาพร้อมใบรับรองการสอบเทียบจากโรงงานและเป็นไปตามมาตรฐานสากล (IEC 61672, ISO 8041)',
    'products.card2Title': 'การรับประกันและการสนับสนุน',
    'products.card2Desc': 'การรับประกันที่ครอบคลุมพร้อมการสนับสนุนทางเทคนิคในประเทศและบริการสอบเทียบภายในประเทศ',
    'products.card3Title': 'คำปรึกษาจากผู้เชี่ยวชาญ',
    'products.card3Desc': 'คำปรึกษาทางเทคนิคฟรีเพื่อช่วยคุณเลือกอุปกรณ์ที่เหมาะสมสำหรับการใช้งานเฉพาะของคุณ',
    'products.card4Title': 'จัดส่งรวดเร็ว',
    'products.card4Desc': 'จัดส่งอย่างรวดเร็วทั่วประเทศไทยและเอเชียตะวันออกเฉียงใต้พร้อมบรรจุภัณฑ์ที่ปลอดภัยและระบบติดตาม',
    'products.browseByCategoryTitle': 'เรียกดูตามหมวดหมู่ผลิตภัณฑ์',
    'products.browseByCategorySubtitle': 'ตั้งแต่เครื่องวัดระดับเสียงแบบพกพาไปจนถึงระบบกล้องอะคูสติกขั้นสูง ค้นหาสิ่งที่คุณต้องการสำหรับการตรวจวัดสิ่งแวดล้อม อะคูสติกอาคาร การควบคุมเสียงในอุตสาหกรรม หรือการวิเคราะห์การสั่นสะเทือน',
    'products.slm.title': 'เครื่องวัดระดับเสียง',
    'products.slm.desc': 'เครื่องวัดระดับเสียงแม่นยำระดับ Class 1 และ Class 2 สำหรับการวัดเสียงสิ่งแวดล้อม อาชีวอนามัย และอะคูสติกอาคาร มีรุ่นแบบพกพาและแบบมือถือ',
    'products.slm.bullet1': 'ได้รับการรับรอง IEC 61672 Class 1 และ Class 2',
    'products.slm.bullet2': 'การวิเคราะห์แบนด์ออกเทฟแบบเรียลไทม์',
    'products.slm.bullet3': 'การบันทึกข้อมูลและการเชื่อมต่อไร้สาย',
    'products.slm.bullet4': 'รวมใบรับรองการสอบเทียบ',
    'products.noise.title': 'ระบบตรวจวัดเสียง',
    'products.noise.desc': 'สถานีตรวจวัดเสียงถาวรและชั่วคราวสำหรับไซต์ก่อสร้าง สนามบิน โรงงานอุตสาหกรรม และการตรวจวัดการปฏิบัติตามข้อกำหนดด้านสิ่งแวดล้อม',
    'products.noise.bullet1': 'ความสามารถในการตรวจวัดต่อเนื่อง 24/7',
    'products.noise.bullet2': 'ตู้กันน้ำสำหรับติดตั้งกลางแจ้ง',
    'products.noise.bullet3': 'การเข้าถึงระยะไกลและการแจ้งเตือน',
    'products.noise.bullet4': 'ซอฟต์แวร์รายงานการปฏิบัติตาม',
    'products.vibration.title': 'อุปกรณ์วิเคราะห์การสั่นสะเทือน',
    'products.vibration.desc': 'เครื่องวัดการสั่นสะเทือน เครื่องวิเคราะห์ และระบบตรวจวัดขั้นสูงสำหรับการตรวจสอบสุขภาพโครงสร้าง การวิเคราะห์เครื่องจักรอุตสาหกรรม และการประเมินการสั่นสะเทือนของอาคาร',
    'products.vibration.bullet1': 'การสั่นสะเทือนที่ส่งผลต่อความสะดวกสบายของมนุษย์ (ISO 2631)',
    'products.vibration.bullet2': 'การประเมินความเสียหายของอาคาร (DIN 4150)',
    'products.vibration.bullet3': 'การตรวจสอบสภาพเครื่องจักร',
    'products.vibration.bullet4': 'ระบบเซ็นเซอร์สามแกน',
    'products.material.title': 'การทดสอบวัสดุอะคูสติก',
    'products.material.desc': 'อุปกรณ์มืออาชีพสำหรับการทดสอบการดูดซับเสียง การกันเสียง และการสูญเสียการส่งผ่านของวัสดุก่อสร้าง แผ่นบอร์ด และการบำบัดอะคูสติก',
    'products.material.bullet1': 'ระบบท่อความต้านทาน (ISO 10534)',
    'products.material.bullet2': 'การวัดการสูญเสียการส่งผ่าน',
    'products.material.bullet3': 'การทดสอบสัมประสิทธิ์การดูดซับ',
    'products.material.bullet4': 'ระบบในห้องปฏิบัติการและภาคสนาม',
    'products.calibration.title': 'ระบบสอบเทียบอะคูสติก',
    'products.calibration.desc': 'เครื่องสอบเทียบอะคูสติกที่แม่นยำ พิสโตนโฟน และระบบสอบเทียบสำหรับการรักษาความแม่นยำในการวัดและการปฏิบัติตามมาตรฐานสากล',
    'products.calibration.bullet1': 'มาตรฐาน Class 1 และ LS',
    'products.calibration.bullet2': 'ตัวเลือกความถี่หลายแบบ',
    'products.calibration.bullet3': 'สอดคล้องกับ IEC 60942',
    'products.calibration.bullet4': 'การสอบเทียบที่สามารถติดตามได้',
    'products.sensors.title': 'เซ็นเซอร์เสียงและการสั่นสะเทือน',
    'products.sensors.desc': 'ไมโครโฟนสำหรับการวัด เซ็นเซอร์วัดความเร่ง และทรานสดิวเซอร์ประสิทธิภาพสูงสำหรับการวัดเสียงและการสั่นสะเทือนที่แม่นยำ',
    'products.sensors.bullet1': 'ไมโครโฟนแบบฟรีฟิลด์และเพรสเชอร์ฟิลด์',
    'products.sensors.bullet2': 'เซ็นเซอร์วัดความเร่งแบบพีโซอิเล็กทริกและ MEMS',
    'products.sensors.bullet3': 'ครอบคลุมช่วงความถี่กว้าง',
    'products.sensors.bullet4': 'ใบรับรองการสอบเทียบจากโรงงาน',
    
    // Applications Page
    'applications.title': 'โซลูชันการทดสอบเสียง เสียงรบกวน และการสั่นสะเทือน',
    'applications.subtitle': 'ค้นหาอุปกรณ์และระบบที่เหมาะสมสำหรับแอปพลิเคชันของคุณ ตั้งแต่อะคูสติกอาคารไปจนถึงการทดสอบอุตสาหกรรม',
    'applications.viewDetails': 'ดูรายละเอียด',
    
    // Guides Page
    'guides.title': 'คู่มือการซื้อผู้เชี่ยวชาญ',
    'guides.subtitle': 'คู่มือฉบับสมบูรณ์เพื่อช่วยคุณเลือกอุปกรณ์วัดเสียง เสียงรบกวน และการสั่นสะเทือนที่เหมาะสมสำหรับความต้องการของคุณ',
    'guides.readTime': 'เวลาอ่าน',
    'guides.level': 'ระดับ',
    'guides.category': 'หมวดหมู่',
    'guides.readGuide': 'อ่านคู่มือ',
    'guides.allGuides': 'คู่มือทั้งหมด',
    'guides.beginner': 'เริ่มต้น',
    'guides.intermediate': 'กลาง',
    'guides.advanced': 'ขั้นสูง',
    
    // Solutions Pages
    'solutions.impedanceTube.title': 'ท่อวัดความต้านทานอะคูสติก ISO 10534-2 & ASTM E2611',
    'solutions.impedanceTube.subtitle': 'ระบบท่อวัดความต้านทานมืออาชีพสำหรับการวัดค่าสัมประสิทธิ์การดูดซับเสียงและการสูญเสียการส่งผ่านตาม ISO 10534-2 และ ASTM E2611',
    'solutions.impedanceTube.compliant': 'สอดคล้องกับ ISO 10534-2 & ASTM E2611',
    'solutions.impedanceTube.accurate': 'การวัดที่แม่นยำและรวดเร็ว',
    'solutions.impedanceTube.support': 'การสนับสนุนและการสอบเทียบในประเทศไทย',
    'solutions.impedanceTube.standards': 'มาตรฐานและการใช้งาน',
    'solutions.impedanceTube.iso10534': 'ISO 10534-2: วิธีฟังก์ชันถ่ายโอนสำหรับการวัดค่าสัมประสิทธิ์การดูดซับเสียง',
    'solutions.impedanceTube.astm': 'ASTM E2611: วิธีมาตรฐานสำหรับการวัดสมบัติเชิงกลของวัสดุอะคูสติก',
    'solutions.impedanceTube.features': 'คุณสมบัติทางเทคนิค',
    'solutions.impedanceTube.fastAccurate': 'รวดเร็วและแม่นยำ',
    'solutions.impedanceTube.fastDesc': 'ผลลัพธ์ภายในไม่กี่นาที ไม่จำเป็นต้องมีห้องปราศจากเสียงสะท้อน',
    'solutions.impedanceTube.broadFreq': 'ช่วงความถี่กว้าง',
    'solutions.impedanceTube.broadFreqDesc': 'วัดตั้งแต่ 50 Hz ถึง 6400 Hz ด้วยท่อขนาดหลายขนาด',
    'solutions.impedanceTube.recognized': 'ได้รับการยอมรับในระดับสากล',
    'solutions.impedanceTube.recognizedDesc': 'ผลลัพธ์ที่ยอมรับสำหรับการรับรองและการวิจัย',
    'solutions.impedanceTube.products': 'ผลิตภัณฑ์ที่แนะนำ',
    'solutions.impedanceTube.consultation': 'ต้องการคำปรึกษา?',
    'solutions.impedanceTube.consultationDesc': 'ทีมผู้เชี่ยวชาญของเราพร้อมช่วยคุณเลือกระบบท่อวัดความต้านทานที่เหมาะสม',
    'solutions.impedanceTube.contactExpert': 'ติดต่อผู้เชี่ยวชาญ',
    'solutions.impedanceTube.viewGuides': 'ดูคู่มือการซื้อ',
    
    'solutions.class1Mic.title': 'ไมโครโฟนวัดระดับเสียงคลาส 1 สำหรับประเทศไทย',
    'solutions.class1Mic.subtitle': 'ไมโครโฟนวัดระดับเสียงความแม่นยำสูง PMP21 Series สอดคล้องกับ IEC 61094-4 พร้อมการสอบเทียบรายตัวและการสนับสนุนในประเทศไทย',
    'solutions.class1Mic.precision': 'ความแม่นยำสูงสุด',
    'solutions.class1Mic.precisionDesc': 'สอดคล้องกับ IEC 61672 คลาส 1 และ IEC 61094-4 สำหรับการวัดที่แม่นยำที่สุด',
    'solutions.class1Mic.calibration': 'การสอบเทียบรายตัว',
    'solutions.class1Mic.calibrationDesc': 'ไมโครโฟนทุกตัวมาพร้อมใบรับรองการสอบเทียบที่สามารถติดตามได้',
    'solutions.class1Mic.localSupport': 'การสนับสนุนในประเทศไทย',
    'solutions.class1Mic.localSupportDesc': 'บริการหลังการขายในประเทศไทย การสอบเทียบ และการสนับสนุนทางเทคนิค',
    'solutions.class1Mic.techSpecs': 'ข้อมูลจำเพาะทางเทคนิค',
    'solutions.class1Mic.pmp21Series': 'PMP21 Series - ไมโครโฟนวัดคลาส 1',
    'solutions.class1Mic.freqRange': 'ช่วงความถี่: 3.15 Hz ถึง 20 kHz',
    'solutions.class1Mic.sensitivity': 'ความไว: 50 mV/Pa ±2 dB',
    'solutions.class1Mic.dynamic': 'ช่วงไดนามิก: 15 dB(A) ถึง 146 dB',
    'solutions.class1Mic.standards': 'มาตรฐาน: IEC 61094-4, IEC 61672 คลาส 1',
    'solutions.class1Mic.compatible': 'เครื่องวัดระดับเสียงที่เข้ากันได้',
    'solutions.class1Mic.applications': 'แอปพลิเคชันทั่วไป',
    'solutions.class1Mic.buildingAcoustics': 'การทดสอบอะคูสติกอาคาร (ISO 16283)',
    'solutions.class1Mic.environmental': 'การตรวจสอบเสียงรบกวนสิ่งแวดล้อม',
    'solutions.class1Mic.industrial': 'การวัดเสียงรบกวนในอุตสาหกรรม',
    'solutions.class1Mic.laboratory': 'การวิจัยและการวัดในห้องปฏิบัติการ',
    'solutions.class1Mic.expertAdvice': 'ต้องการคำแนะนำจากผู้เชี่ยวชาญ?',
    'solutions.class1Mic.expertAdviceDesc': 'ติดต่อเราเพื่อหารือเกี่ยวกับความต้องการในการวัดเสียงของคุณและค้นหาโซลูชันไมโครโฟนที่เหมาะสม',
    'solutions.class1Mic.getQuote': 'ขอใบเสนอราคา',
    'solutions.class1Mic.browseAll': 'ดูผลิตภัณฑ์ทั้งหมด',
    
    'solutions.factoryNoise.title': 'ระบบตรวจสอบเสียงรบกวนในโรงงาน',
    'solutions.factoryNoise.subtitle': 'โซลูชันการตรวจสอบเสียงรบกวนอย่างต่อเนื่องสำหรับสภาพแวดล้อมอุตสาหกรรม ความปลอดภัยของพนักงาน และการปฏิบัติตามกฎระเบียบสิ่งแวดล้อมในประเทศไทย',
    'solutions.factoryNoise.viewSolutions': 'ดูโซลูชัน',
    'solutions.factoryNoise.requestConsultation': 'ขอคำปรึกษา',
    
    'solutions.eolTesting.title': 'การทดสอบอะคูสติก End-of-Line',
    'solutions.eolTesting.subtitle': 'ระบบทดสอบอะคูสติกอัตโนมัติสำหรับการควบคุมคุณภาพในสายการผลิต รวมท่อวัดความต้านทานและไมโครโฟนวัดความแม่นยำสูง',
    'solutions.eolTesting.viewEquipment': 'ดูอุปกรณ์',
    'solutions.eolTesting.requestConsultation': 'ขอคำปรึกษา',
  }
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState('en')
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
    // Load language from localStorage
    const savedLanguage = localStorage?.getItem('language')
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'th')) {
      setLanguageState(savedLanguage)
    }
  }, [])

  const setLanguage = (lang: string) => {
    if (lang === 'en' || lang === 'th') {
      setLanguageState(lang)
      localStorage?.setItem('language', lang)
      // Dispatch a custom event to notify other components
      window?.dispatchEvent?.(new CustomEvent('languageChange', { detail: lang }))
    }
  }

  // Don't render until mounted to avoid hydration issues
  if (!mounted) {
    return null
  }

  const t = (key: string) => {
    return translations?.[language]?.[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}