
"use client"

import React, { createContext, useContext, useState, useEffect } from 'react'

interface LanguageContextType {
  language: string
  setLanguage: (lang: string) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations: Record<string, Record<string, string>> = {
  en: {
    'site.title': 'Placid Asia - Professional Acoustic Solutions',
    'site.description': 'Leading supplier of acoustic measurement equipment and sound testing solutions in Asia',
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.categories': 'Categories',
    'nav.brands': 'Brands',
    'nav.applications': 'Applications',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.admin': 'Admin',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    'nav.cart': 'Cart',
    'hero.title': 'Professional Acoustic Measurement Solutions',
    'hero.subtitle': 'Precision instruments for sound measurement, vibration analysis, and acoustic testing across industries',
    'hero.cta': 'Explore Products',
    'products.title': 'Our Products',
    'products.subtitle': 'Comprehensive range of acoustic measurement equipment',
    'products.search': 'Search products...',
    'products.filter': 'Filter by category',
    'products.sort': 'Sort by',
    'products.sort.name': 'Name',
    'products.sort.category': 'Category',
    'products.addToCart': 'Add to Cart',
    'products.contactForQuote': 'Contact for Quote',
    'products.viewDetails': 'View Details',
    'products.downloadPDF': 'Download PDF',
    'categories.title': 'Product Categories',
    'categories.products': 'products',
    'categories.label': 'Categories',
    'categories.backToCategories': 'Back to Categories',
    'categories.inCategory': 'products in this category',
    'cart.title': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.quantity': 'Quantity',
    'cart.remove': 'Remove',
    'cart.total': 'Total Items',
    'cart.loading': 'Loading cart...',
    'cart.startShopping': 'Start shopping to add items to your cart',
    'cart.continueShopping': 'Continue Shopping',
    'cart.itemsInCart': 'items in your cart',
    'cart.clearCart': 'Clear Cart',
    'cart.requestQuote': 'Request Quote',
    'cart.sku': 'SKU:',
    'cart.category': 'Category:',
    'contact.title': 'Contact Us',
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.phone': 'Phone',
    'contact.company': 'Company',
    'contact.subject': 'Subject',
    'contact.message': 'Message',
    'contact.submit': 'Send Message',
    'contact.success': 'Thank you! Your message has been sent.',
    'contact.description': 'Get in touch with our team for product inquiries, technical support, or partnership opportunities',
    'contact.sendMessage': 'Send us a message',
    'contact.namePlaceholder': 'Your full name',
    'contact.emailPlaceholder': 'your.email@company.com',
    'contact.phonePlaceholder': '+66 xx xxx xxxx',
    'contact.companyPlaceholder': 'Your company name',
    'contact.productSku': 'Product SKU',
    'contact.subjectPlaceholder': 'How can we help you?',
    'contact.messagePlaceholder': 'Please provide details about your inquiry...',
    'contact.sending': 'Sending...',
    'contact.info': 'Contact Information',
    'contact.email.label': 'Email',
    'contact.phone.label': 'Phone',
    'contact.address': 'Address',
    'contact.address.value': 'Bangkok, Thailand',
    'contact.businessHours': 'Business Hours',
    'contact.monday-friday': 'Monday - Friday',
    'contact.saturday': 'Saturday',
    'contact.sunday': 'Sunday',
    'contact.closed': 'Closed',
    'contact.formDescription': 'Fill out the form below and we\'ll get back to you as soon as possible.',
    'contact.infoDescription': 'You can also reach us through these channels',
    'contact.whyChooseUs': 'Why Choose Placid Asia?',
    'contact.reason1': 'Fast response within 24 hours',
    'contact.reason2': 'Expert technical support',
    'contact.reason3': 'Tailored solutions for your needs',
    'contact.reason4': 'Long-term partnership commitment',
    'footer.about': 'About Placid Asia',
    'footer.description': 'Leading supplier of professional acoustic measurement equipment and solutions across Asia Pacific region.',
    'footer.links': 'Quick Links',
    'footer.contact': 'Contact Info',
    'footer.rights': 'All rights reserved',
    'admin.title': 'Admin Dashboard',
    'admin.products': 'Products',
    'admin.categories': 'Categories',
    'admin.inquiries': 'Inquiries',
    'admin.users': 'Users',
    'admin.totalProducts': 'Total Products',
    'admin.withPricing': 'with pricing',
    'admin.withoutPricing': 'without',
    'admin.activeCategories': 'Active product categories',
    'admin.totalInquiries': 'Total Inquiries',
    'admin.customerInquiries': 'Customer inquiries received',
    'admin.adminUsers': 'Admin Users',
    'admin.activeAccounts': 'Active admin accounts',
    'admin.dashboard': 'Admin Dashboard',
    'admin.welcomeBack': 'Welcome back',
    'admin.manageMessage': 'Manage your acoustic equipment catalog.',
    'admin.recentInquiries': 'Recent Inquiries',
    'admin.product': 'Product:',
    'admin.noInquiries': 'No inquiries yet',
    'admin.quickActions': 'Quick Actions',
    'admin.productManagement': 'Product Management',
    'admin.productManagementDesc': 'Add new products, update pricing, manage categories',
    'admin.inquiryManagement': 'Inquiry Management',
    'admin.inquiryManagementDesc': 'Review customer inquiries and product requests',
    'admin.contentUpdates': 'Content Updates',
    'admin.contentUpdatesDesc': 'Update product descriptions, images, and documentation',
    'product.documents': 'Documents',
    'product.getInfo': 'Get More Information',
    'product.contactPlacid': 'Contact Placid Asia',
    'product.manufacturerPage': 'Manufacturer Page',
    'product.description': 'Description',
    'product.applications': 'Typical Applications',
    'product.features': 'Key Features',
    'product.specifications': 'Technical Specifications',
    'product.resources': 'Resources & Downloads',
    'product.overview': 'In-Depth Overview',
    'product.applicationsDesc': 'Common use cases and application scenarios for this product',
    'product.featuresTitle': 'Key Features & Benefits',
    'product.featuresDesc': 'What makes this product stand out from the competition',
    'product.specsTitle': 'Technical Specifications',
    'product.specsDesc': 'Detailed technical parameters and performance characteristics',
    'product.downloadDoc': 'Download Documentation',
    'product.viewManual': 'View Product Manual',
    'product.relatedProducts': 'Related Products',
    'product.relatedDesc': 'You might also be interested in these products',
    'product.parameter': 'Parameter',
    'product.specification': 'Specification',
    'common.back': 'Back to Products',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
  },
  th: {
    'site.title': 'Placid Asia - โซลูชันอะคูสติกระดับมืออาชีพ',
    'site.description': 'ผู้จัดจำหน่ายชั้นนำของอุปกรณ์วัดเสียงและโซลูชันการทดสอบเสียงในเอเชีย',
    'nav.home': 'หน้าแรก',
    'nav.products': 'ผลิตภัณฑ์',
    'nav.categories': 'หมวดหมู่',
    'nav.brands': 'แบรนด์',
    'nav.applications': 'การใช้งาน',
    'nav.about': 'เกี่ยวกับเรา',
    'nav.contact': 'ติดต่อ',
    'nav.admin': 'ผู้ดูแลระบบ',
    'nav.login': 'เข้าสู่ระบบ',
    'nav.logout': 'ออกจากระบบ',
    'nav.cart': 'ตะกร้า',
    'hero.title': 'โซลูชันการวัดเสียงระดับมืออาชีพ',
    'hero.subtitle': 'เครื่องมือแม่นยำสำหรับการวัดเสียง การวิเคราะห์การสั่นสะเทือน และการทดสอบอะคูสติกในอุตสาหกรรมต่างๆ',
    'hero.cta': 'ดูผลิตภัณฑ์',
    'products.title': 'ผลิตภัณฑ์ของเรา',
    'products.subtitle': 'ผลิตภัณฑ์อุปกรณ์วัดเสียงครบครัน',
    'products.search': 'ค้นหาผลิตภัณฑ์...',
    'products.filter': 'กรองตามหมวดหมู่',
    'products.sort': 'เรียงตาม',
    'products.sort.name': 'ชื่อ',
    'products.sort.category': 'หมวดหมู่',
    'products.addToCart': 'เพิ่มลงตะกร้า',
    'products.contactForQuote': 'ติดต่อสอบถามราคา',
    'products.viewDetails': 'ดูรายละเอียด',
    'products.downloadPDF': 'ดาวน์โหลด PDF',
    'categories.title': 'หมวดหมู่ผลิตภัณฑ์',
    'categories.products': 'ผลิตภัณฑ์',
    'categories.label': 'หมวดหมู่',
    'categories.backToCategories': 'กลับไปที่หมวดหมู่',
    'categories.inCategory': 'ผลิตภัณฑ์ในหมวดหมู่นี้',
    'cart.title': 'ตะกร้าสินค้า',
    'cart.empty': 'ตะกร้าของคุณว่างเปล่า',
    'cart.quantity': 'จำนวน',
    'cart.remove': 'ลบ',
    'cart.total': 'จำนวนรายการทั้งหมด',
    'cart.loading': 'กำลังโหลดตะกร้า...',
    'cart.startShopping': 'เริ่มช็อปปิ้งเพื่อเพิ่มสินค้าในตะกร้าของคุณ',
    'cart.continueShopping': 'ช็อปปิ้งต่อ',
    'cart.itemsInCart': 'รายการในตะกร้าของคุณ',
    'cart.clearCart': 'ล้างตะกร้า',
    'cart.requestQuote': 'ขอใบเสนอราคา',
    'cart.sku': 'รหัสสินค้า:',
    'cart.category': 'หมวดหมู่:',
    'contact.title': 'ติดต่อเรา',
    'contact.name': 'ชื่อ',
    'contact.email': 'อีเมล',
    'contact.phone': 'โทรศัพท์',
    'contact.company': 'บริษัท',
    'contact.subject': 'หัวข้อ',
    'contact.message': 'ข้อความ',
    'contact.submit': 'ส่งข้อความ',
    'contact.success': 'ขอบคุณ! ข้อความของคุณถูกส่งแล้ว',
    'contact.description': 'ติดต่อทีมของเราสำหรับข้อมูลผลิตภัณฑ์ การสนับสนุนทางเทคนิค หรือโอกาสในการเป็นพันธมิตร',
    'contact.sendMessage': 'ส่งข้อความถึงเรา',
    'contact.namePlaceholder': 'ชื่อเต็มของคุณ',
    'contact.emailPlaceholder': 'อีเมลของคุณ@บริษัท.com',
    'contact.phonePlaceholder': '+66 xx xxx xxxx',
    'contact.companyPlaceholder': 'ชื่อบริษัทของคุณ',
    'contact.productSku': 'รหัสผลิตภัณฑ์',
    'contact.subjectPlaceholder': 'เราสามารถช่วยคุณอย่างไร?',
    'contact.messagePlaceholder': 'โปรดระบุรายละเอียดเกี่ยวกับคำถามของคุณ...',
    'contact.sending': 'กำลังส่ง...',
    'contact.info': 'ข้อมูลติดต่อ',
    'contact.email.label': 'อีเมล',
    'contact.phone.label': 'โทรศัพท์',
    'contact.address': 'ที่อยู่',
    'contact.address.value': 'กรุงเทพฯ ประเทศไทย',
    'contact.businessHours': 'เวลาทำการ',
    'contact.monday-friday': 'จันทร์ - ศุกร์',
    'contact.saturday': 'เสาร์',
    'contact.sunday': 'อาทิตย์',
    'contact.closed': 'ปิดทำการ',
    'contact.formDescription': 'กรอกแบบฟอร์มด้านล่างและเราจะติดต่อกลับโดยเร็วที่สุด',
    'contact.infoDescription': 'คุณสามารถติดต่อเราผ่านช่องทางเหล่านี้',
    'contact.whyChooseUs': 'ทำไมต้องเลือก Placid Asia?',
    'contact.reason1': 'ตอบกลับอย่างรวดเร็วภายใน 24 ชั่วโมง',
    'contact.reason2': 'การสนับสนุนทางเทคนิคจากผู้เชี่ยวชาญ',
    'contact.reason3': 'โซลูชันที่ปรับแต่งตามความต้องการของคุณ',
    'contact.reason4': 'มุ่งมั่นในความร่วมมือระยะยาว',
    'footer.about': 'เกี่ยวกับ Placid Asia',
    'footer.description': 'ผู้จัดจำหน่ายชั้นนำของอุปกรณ์วัดเสียงระดับมืออาชีพและโซลูชันต่างๆ ในภูมิภาคเอเชียแปซิฟิก',
    'footer.links': 'ลิงค์ด่วน',
    'footer.contact': 'ข้อมูลติดต่อ',
    'footer.rights': 'สงวนลิขสิทธิ์',
    'admin.title': 'แดชบอร์ดผู้ดูแลระบบ',
    'admin.products': 'ผลิตภัณฑ์',
    'admin.categories': 'หมวดหมู่',
    'admin.inquiries': 'คำถาม',
    'admin.users': 'ผู้ใช้',
    'admin.totalProducts': 'ผลิตภัณฑ์ทั้งหมด',
    'admin.withPricing': 'มีราคา',
    'admin.withoutPricing': 'ไม่มีราคา',
    'admin.activeCategories': 'หมวดหมู่ผลิตภัณฑ์ที่ใช้งาน',
    'admin.totalInquiries': 'คำถามทั้งหมด',
    'admin.customerInquiries': 'คำถามจากลูกค้าที่ได้รับ',
    'admin.adminUsers': 'ผู้ดูแลระบบ',
    'admin.activeAccounts': 'บัญชีผู้ดูแลที่ใช้งาน',
    'admin.dashboard': 'แดชบอร์ดผู้ดูแลระบบ',
    'admin.welcomeBack': 'ยินดีต้อนรับกลับ',
    'admin.manageMessage': 'จัดการแคตตาล็อกอุปกรณ์อะคูสติกของคุณ',
    'admin.recentInquiries': 'คำถามล่าสุด',
    'admin.product': 'ผลิตภัณฑ์:',
    'admin.noInquiries': 'ยังไม่มีคำถาม',
    'admin.quickActions': 'การดำเนินการด่วน',
    'admin.productManagement': 'การจัดการผลิตภัณฑ์',
    'admin.productManagementDesc': 'เพิ่มผลิตภัณฑ์ใหม่ อัพเดทราคา จัดการหมวดหมู่',
    'admin.inquiryManagement': 'การจัดการคำถาม',
    'admin.inquiryManagementDesc': 'ตรวจสอบคำถามจากลูกค้าและคำขอผลิตภัณฑ์',
    'admin.contentUpdates': 'การอัพเดทเนื้อหา',
    'admin.contentUpdatesDesc': 'อัพเดทคำอธิบายผลิตภัณฑ์ รูปภาพ และเอกสาร',
    'product.documents': 'เอกสาร',
    'product.getInfo': 'ขอข้อมูลเพิ่มเติม',
    'product.contactPlacid': 'ติดต่อ Placid Asia',
    'product.manufacturerPage': 'หน้าผู้ผลิต',
    'product.description': 'รายละเอียด',
    'product.applications': 'การใช้งานทั่วไป',
    'product.features': 'คุณสมบัติสำคัญ',
    'product.specifications': 'ข้อมูลทางเทคนิค',
    'product.resources': 'ทรัพยากรและดาวน์โหลด',
    'product.overview': 'ภาพรวมโดยละเอียด',
    'product.applicationsDesc': 'กรณีการใช้งานทั่วไปและสถานการณ์การใช้งานสำหรับผลิตภัณฑ์นี้',
    'product.featuresTitle': 'คุณสมบัติและประโยชน์หลัก',
    'product.featuresDesc': 'สิ่งที่ทำให้ผลิตภัณฑ์นี้โดดเด่นจากคู่แข่ง',
    'product.specsTitle': 'ข้อมูลทางเทคนิค',
    'product.specsDesc': 'พารามิเตอร์ทางเทคนิคและลักษณะประสิทธิภาพโดยละเอียด',
    'product.downloadDoc': 'ดาวน์โหลดเอกสาร',
    'product.viewManual': 'ดูคู่มือผลิตภัณฑ์',
    'product.relatedProducts': 'ผลิตภัณฑ์ที่เกี่ยวข้อง',
    'product.relatedDesc': 'คุณอาจสนใจผลิตภัณฑ์เหล่านี้',
    'product.parameter': 'พารามิเตอร์',
    'product.specification': 'ข้อกำหนด',
    'common.back': 'กลับไปที่ผลิตภัณฑ์',
    'common.loading': 'กำลังโหลด...',
    'common.error': 'ข้อผิดพลาด',
    'common.success': 'สำเร็จ',
  }
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState('en')
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
    // Load language from localStorage
    const savedLanguage = localStorage?.getItem('language')
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'th')) {
      setLanguageState(savedLanguage)
    }
  }, [])

  const setLanguage = (lang: string) => {
    if (lang === 'en' || lang === 'th') {
      setLanguageState(lang)
      localStorage?.setItem('language', lang)
      // Dispatch a custom event to notify other components
      window?.dispatchEvent?.(new CustomEvent('languageChange', { detail: lang }))
    }
  }

  // Don't render until mounted to avoid hydration issues
  if (!mounted) {
    return null
  }

  const t = (key: string) => {
    return translations?.[language]?.[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}